package tech.tanzx.coordinatorlayoutdemo.repo

import tech.tanzx.coordinatorlayoutdemo.R
import tech.tanzx.coordinatorlayoutdemo.entity.Person

object PersonProvider {

    private val persons by lazy {
        listOf(
            Person(name = "用户1", images = listOf(
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
            )),
            Person(name = "用户2", images = listOf(
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
            )),
            Person(name = "用户3", images = listOf(
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
            )),
            Person(name = "用户4", images = listOf(
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
            )),
            Person(name = "用户5", images = listOf(
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
            )),
            Person(name = "用户6", images = listOf(
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
            )),
            Person(name = "用户7", images = listOf(
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
            )),
            Person(name = "用户8", images = listOf(
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
            )),
            Person(name = "用户9", images = listOf(
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
            )),
            Person(name = "用户10", images = listOf(
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
            )),
            Person(name = "用户11", images = listOf(
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
            )),
            Person(name = "用户12", images = listOf(
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
            )),
            Person(name = "用户13", images = listOf(
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
            )),
            Person(name = "用户14", images = listOf(
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
            )),
            Person(name = "用户15", images = listOf(
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
            )),
            Person(name = "用户15", images = listOf(
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
            )),
            Person(name = "用户15", images = listOf(
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
            )),
            Person(name = "用户15", images = listOf(
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
            )),
            Person(name = "用户15", images = listOf(
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
            )),
            Person(name = "用户15", images = listOf(
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
            )),
            Person(name = "用户15", images = listOf(
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
            )),
            Person(name = "用户15", images = listOf(
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
            )),
            Person(name = "用户15", images = listOf(
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
            )),
            Person(name = "用户15", images = listOf(
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
            )),
            Person(name = "用户15", images = listOf(
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
                R.drawable.classify_zhiyu,
            )),
        )

    }

    fun getPerson(): List<Person> {
        return persons
    }
}